name = "codyssi"
version = "1.0.0"

[dependencies]
argv = "~> 1.0"
gleam_stdlib = "~> 0.34 or ~> 1.0"
simplifile = "~> 2.0"
gleam_regexp = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
