# name: Build Docker Image
#
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
#   schedule:
#     # run every night at 2:02 UTC (tests are scheduled at 2:42, so they are
#     # guaranteed to have a freshly built Docker image)
#     - cron: '2 2 * * *'
#
# env:
#   IMAGE_NAME: yogans-advent-of-code
#
# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#
#     permissions:
#       packages: write
#       contents: read
#
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 2
#
#       - name: Check Git changes
#         id: git-diff-check
#         run: ./scripts/check-git-changes.sh ${{ github.sha }}
#
#       - name: Build and push image
#         if: ${{ github.event.schedule || steps.git-diff-check.outputs.changes-docker != '0' }}
#         run: |
#           docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
#           echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
#           IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
#           IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
#           VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
#           [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
#           [ "$VERSION" == "main" ] && VERSION=latest
#           echo IMAGE_ID=$IMAGE_ID
#           echo VERSION=$VERSION
#           docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
#           docker push $IMAGE_ID:$VERSION
