name: Check README Links

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # run every night at 2:42 UTC (3:42/4:42 German time)
    - cron: '42 3 * * *'

jobs:
  linkspector:
    # runs-on: ubuntu-latest
    # ↑ fails with "No usable sandbox!", see:
    # https://github.com/puppeteer/puppeteer/issues/12818
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Check READMEs
        run: npx @umbrelladocs/linkspector check --config .linkspector-github.yml
