name: Check READMEs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # run every night at 2:42 UTC (3:42/4:42 German time)
    - cron: '42 3 * * *'

jobs:
  markdown-link-check-script:
    runs-on: ubuntu-latest
    container: ghcr.io/yogan/yogans-advent-of-code:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check READMEs
        run: ./scripts/check-readmes.sh

  markdown-link-check-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
