name: Test Templates

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest

    outputs:
      changes-ci: ${{ steps.git-diff-check.outputs.changes-ci }}
      changes-scripts: ${{ steps.git-diff-check.outputs.changes-scripts }}
      changes-templates: ${{ steps.git-diff-check.outputs.changes-templates }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check Git changes
        id: git-diff-check
        run: ./scripts/check-git-changes.sh ${{ github.sha }}

  test-templates:
    runs-on: ubuntu-latest
    container: ghcr.io/yogan/yogans-advent-of-code:latest

    needs: check-changes
    if: ${{ needs.check-changes.outputs.templates != '0' || needs.check-changes.outputs.changes-ci != '0' || needs.check-changes.outputs.changes-scripts != '0' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test templates
        run: ./scripts/test-templates.sh
