name: Test Templates

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-templates:
    runs-on: ubuntu-latest
    container: ghcr.io/yogan/yogans-advent-of-code:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test templates
        run: ./test-templates.sh
