name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t yogans-advent-of-code .

    - name: Test templates
      run: docker run yogans-advent-of-code ./test-templates.sh

    - name: Test solutions
      run: docker run yogans-advent-of-code ./test-solutions.sh
