name: Test Templates

on:
  push:
  pull_request:
  schedule:
    # run every night at 2:42 UTC (3:42/4:42 German time)
    - cron: '42 3 * * *'

jobs:
  check-changes:
    runs-on: ubuntu-latest

    outputs:
      changes-ci: ${{ steps.git-diff-check.outputs.changes-ci }}
      changes-scripts: ${{ steps.git-diff-check.outputs.changes-scripts }}
      changes-templates: ${{ steps.git-diff-check.outputs.changes-templates }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check Git changes
        id: git-diff-check
        run: ./scripts/check-git-changes.sh ${{ github.sha }}

  test-templates:
    runs-on: ubuntu-latest
    container: ghcr.io/yogan/yogans-advent-of-code:latest

    needs: check-changes
    if: ${{ github.event.schedule || needs.check-changes.outputs.changes-templates != '0' || needs.check-changes.outputs.changes-ci != '0' || needs.check-changes.outputs.changes-scripts != '0' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Increase disk space by deleting unnecessary stuff
        run: |
          df -h | grep root | awk '{print $4}'
          rm -rf /__t/CodeQL /__t/Python /__t/PyPy /__t/node /__t/go /__t/Ruby
          df -h | grep root | awk '{print $4}'

      - name: Test templates
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          ./scripts/haskell-prepare.sh
          ./scripts/test-templates.sh
          ./scripts/cleanup.sh
